/**
 * integration.smoke.test.ts — ONE live smoke against the demo key.
 *
 * Per plan hard rule: maximum 1-2 API calls in this test.
 * Demo tier: 3 req/min, 50/month — keep it tight.
 *
 * Runs when DOCJET_DEMO_KEY env var is set OR uses the hardcoded demo key
 * from 05-01-SUMMARY.md (PUBLIC BY DESIGN — D-52).
 *
 * Gate: only runs when DOCJET_SMOKE env var is set to 'true'.
 * Normal `npm test` skips this file entirely; the executor runs it explicitly.
 */
import { describe, it, expect } from 'vitest';
import { DocJetClient } from '../index.js';

// Demo key: PUBLIC BY DESIGN (D-52, 05-01-SUMMARY.md)
const DEMO_KEY =
  process.env.DOCJET_DEMO_KEY ??
  'binfra_9afb57dbb6478c441ad101129fca65847f5745403f9d718b3de6d934c9b63f88';

const SMOKE_ENABLED = process.env.DOCJET_SMOKE === 'true';

describe('DocJetClient live smoke', () => {
  it.skipIf(!SMOKE_ENABLED)(
    'render() returns a URL from the live API using the demo key',
    async () => {
      const client = new DocJetClient({ apiKey: DEMO_KEY });
      // Use raw HTML to avoid template-specific required field validation
      // (template required fields vary; HTML path always works with any data)
      const result = await client.render({
        html: '<h1>DocJet SDK smoke test</h1><p>Generated by docjet npm package integration test.</p>',
        data: {},
      });

      expect(result).toBeDefined();
      expect(typeof result.url).toBe('string');
      expect(result.url).toMatch(/^https?:\/\//);
    },
    30_000, // 30s timeout for live API call
  );
});
